/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa093;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.geom.Point2D;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Controller for my View. Creates points, manages them 
 * and calls advance Geometric libraries from Canvas class.
 * 
 * @author Zan Richard
 */
public class Application extends javax.swing.JFrame {
    
    //State for points management.
    public enum State{
        nothingState,
        addState,
        removeState,
        moveState
    }
    
    private State state;
    private Color selectedColor;
    private Points points;
    private Canvas canvas;
    
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        setMainIcon();
        
        canvas = new Canvas();
        canvas.setLayout(new BorderLayout());
        canvas.setSize(DrawingPanel.getWidth(), DrawingPanel.getHeight());
        canvas.setBackground(Color.WHITE);
        DrawingPanel.add(canvas, BorderLayout.CENTER);
        
        
        this.WhiteButtons();
        WhiteControlButtons();
        this.state = State.nothingState;
        this.selectedColor = new Color(153,204,255);
        this.points = new Points();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        randomButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        eraseButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        GiftWrappingButton = new javax.swing.JButton();
        GrahamScanButton = new javax.swing.JButton();
        TriangulationButton = new javax.swing.JButton();
        KDTreeButton = new javax.swing.JButton();
        DelaunayTrianButton = new javax.swing.JButton();
        VoronoiDiagButton = new javax.swing.JButton();
        DrawingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PA093 ");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        randomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa093/Icons/random.png"))); // NOI18N
        randomButton.setText("Random");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa093/Icons/Add.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa093/Icons/Remove.png"))); // NOI18N
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        moveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa093/Icons/Move.png"))); // NOI18N
        moveButton.setText("Move");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        eraseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa093/Icons/Erase.png"))); // NOI18N
        eraseButton.setText("Erase");
        eraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(randomButton)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addGap(18, 18, 18)
                .addComponent(moveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(eraseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(randomButton)
                        .addComponent(addButton)
                        .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        GiftWrappingButton.setText("Gift wrapping ");
        GiftWrappingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiftWrappingButtonActionPerformed(evt);
            }
        });

        GrahamScanButton.setText("Graham Scan");
        GrahamScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrahamScanButtonActionPerformed(evt);
            }
        });

        TriangulationButton.setText("Triangulation");
        TriangulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangulationButtonActionPerformed(evt);
            }
        });

        KDTreeButton.setText("k-D tree");
        KDTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KDTreeButtonActionPerformed(evt);
            }
        });

        DelaunayTrianButton.setText("<html> \nDelaunay's <br>\ntriangulation\n</html>");
        DelaunayTrianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelaunayTrianButtonActionPerformed(evt);
            }
        });

        VoronoiDiagButton.setText("<html> \nVoronoi <br>\ndiagram\n</html>");
        VoronoiDiagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoronoiDiagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoronoiDiagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrahamScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GiftWrappingButton)
                    .addComponent(TriangulationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KDTreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelaunayTrianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(GiftWrappingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GrahamScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TriangulationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KDTreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DelaunayTrianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VoronoiDiagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DrawingPanel.setBackground(new java.awt.Color(0, 0, 0));
        DrawingPanel.setForeground(new java.awt.Color(255, 255, 255));
        DrawingPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseDragged(evt);
            }
        });
        DrawingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrawingPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DrawingPanelLayout = new javax.swing.GroupLayout(DrawingPanel);
        DrawingPanel.setLayout(DrawingPanelLayout);
        DrawingPanelLayout.setHorizontalGroup(
            DrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DrawingPanelLayout.setVerticalGroup(
            DrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold desc="Buttons events">
    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        this.WhiteButtons();
        this.randomButton.setBackground(selectedColor);
        this.state = State.nothingState;
        points = randomPointsGenerator(); 
        canvas.SetPoints(points);
        canvas.repaint();
    }//GEN-LAST:event_randomButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        this.WhiteButtons();
        this.addButton.setBackground(selectedColor);
        this.state = State.addState;
    }//GEN-LAST:event_addButtonActionPerformed

    private void eraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseButtonActionPerformed
        this.WhiteButtons();
        this.eraseButton.setBackground(selectedColor);
        this.state = State.nothingState;
        points = new Points(); 
        canvas.SetPoints(points);
        canvas.repaint();
    }//GEN-LAST:event_eraseButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        this.WhiteButtons();
        this.moveButton.setBackground(selectedColor); 
        this.state = State.moveState;
    }//GEN-LAST:event_moveButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        this.WhiteButtons();
        this.removeButton.setBackground(selectedColor);
        this.state = State.removeState;
    }//GEN-LAST:event_removeButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
       if (canvas != null){
          canvas.setSize(DrawingPanel.getWidth(), DrawingPanel.getHeight()); 
       }
    }//GEN-LAST:event_formComponentResized

    private void DrawingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMousePressed
        if (state != State.moveState){
            doStuff(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_DrawingPanelMousePressed

    private void DrawingPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseDragged
        if (state == State.moveState){
            doStuff(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_DrawingPanelMouseDragged

    private void GiftWrappingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiftWrappingButtonActionPerformed
        if (!this.GiftWrappingButton.getBackground().equals(selectedColor)){
            this.GiftWrappingButton.setBackground(selectedColor);
        } else {
            this.GiftWrappingButton.setBackground(Color.WHITE);
        }
        
        canvas.EnableGiftWrapping();
        canvas.repaint();
    }//GEN-LAST:event_GiftWrappingButtonActionPerformed

    private void GrahamScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrahamScanButtonActionPerformed
        if (!this.GrahamScanButton.getBackground().equals(selectedColor)){
            this.GrahamScanButton.setBackground(selectedColor);
        } else {
            this.GrahamScanButton.setBackground(Color.WHITE);
        }
        
        canvas.EnableGrahamScan();
        canvas.repaint();
    }//GEN-LAST:event_GrahamScanButtonActionPerformed

    private void TriangulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangulationButtonActionPerformed
        if (!this.TriangulationButton.getBackground().equals(selectedColor)){
            this.TriangulationButton.setBackground(selectedColor);
        } else {
            this.TriangulationButton.setBackground(Color.WHITE);
        }
        
        canvas.EnableTriangulation();
        canvas.repaint();
    }//GEN-LAST:event_TriangulationButtonActionPerformed

    private void KDTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KDTreeButtonActionPerformed
        if (!this.KDTreeButton.getBackground().equals(selectedColor)){
            this.KDTreeButton.setBackground(selectedColor);
        } else {
            this.KDTreeButton.setBackground(Color.WHITE);
        }
        
        canvas.EnableKDTree();
        canvas.repaint();
    }//GEN-LAST:event_KDTreeButtonActionPerformed

    private void DelaunayTrianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelaunayTrianButtonActionPerformed
        if (!this.DelaunayTrianButton.getBackground().equals(selectedColor)){
            this.DelaunayTrianButton.setBackground(selectedColor);
        } else {
            this.DelaunayTrianButton.setBackground(Color.WHITE);
        }
       
        canvas.EnableDelaunayTrian();
        canvas.repaint();
    }//GEN-LAST:event_DelaunayTrianButtonActionPerformed

    private void VoronoiDiagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoronoiDiagButtonActionPerformed
        if (!this.VoronoiDiagButton.getBackground().equals(selectedColor)){
            this.VoronoiDiagButton.setBackground(selectedColor);
        } else {
            this.VoronoiDiagButton.setBackground(Color.WHITE);
        }
        
        canvas.EnableVoronoiDiag();
        canvas.repaint();
    }//GEN-LAST:event_VoronoiDiagButtonActionPerformed
    // </editor-fold>
    
    // <editor-fold desc="Main functionality.">
    private void setMainIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/mainIcon.png")));
    }
    
    private void WhiteButtons(){
        this.randomButton.setBackground(Color.WHITE);
        this.addButton.setBackground(Color.WHITE);
        this.removeButton.setBackground(Color.WHITE);
        this.moveButton.setBackground(Color.WHITE);
        this.eraseButton.setBackground(Color.WHITE);
    }
    
    private void WhiteControlButtons(){
        this.GiftWrappingButton.setBackground(Color.WHITE);
        this.GrahamScanButton.setBackground(Color.WHITE);
        this.TriangulationButton.setBackground(Color.WHITE);
        this.KDTreeButton.setBackground(Color.WHITE);
        this.DelaunayTrianButton.setBackground(Color.WHITE);
        this.VoronoiDiagButton.setBackground(Color.WHITE);
    }
    
    private void doStuff(double x, double y){
        switch (state){
            case nothingState: break;
            case addState: 
                points.AddPoint(x, y); 
                canvas.SetPoints(points);
                canvas.repaint();
                break;
            case removeState: 
                points.RemovePoint(x, y); 
                canvas.SetPoints(points);
                canvas.repaint();
                break;
            case moveState: 
                points.MovePoint(x, y); 
                canvas.SetPoints(points);
                canvas.repaint();
                break;
        }
                
    }
    
    private Points randomPointsGenerator(){
        Points tempPoints = new Points();
        
        for (Point2D point : points.GetPoints()){
            tempPoints.AddPoint(point.getX(), point.getY());
        }
        
        Random rand = new Random();
        
        for(int i = 0; i< 6; i++){
            int x = rand.nextInt(canvas.getWidth()-100)+50;
            int y = rand.nextInt(canvas.getHeight()-100)+50;
            tempPoints.AddPoint((double) x, (double) y);
        }

        return tempPoints;
    }
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // <editor-fold desc="GUI variables.">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelaunayTrianButton;
    private javax.swing.JPanel DrawingPanel;
    private javax.swing.JButton GiftWrappingButton;
    private javax.swing.JButton GrahamScanButton;
    private javax.swing.JButton KDTreeButton;
    private javax.swing.JButton TriangulationButton;
    private javax.swing.JButton VoronoiDiagButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton eraseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton randomButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
